onion/urls.py
from django.conf.urls import url
from django.conf.urls import patterns

from django.utils.translation import ugettext_lazy as _

app_name = 'onion'
urlpatterns = patterns('onion.views',
                       url(_(r'^$'), 'index', name='index'),
                       url(_(r'^send/$'), 'send', name='send'),
                       # url(_(r'^isit/$'), 'is_it', name='is_it'),
                       )

onion/models.py
from django.db import models

from django.utils.translation import ugettext_lazy as _

class Hit(models.Model):
    timestamp = models.DateTimeField(verbose_name=_("Time submitted"), auto_now=True)
    url = models.URLField(verbose_name=_('URL'))
    domain = models.TextField(verbose_name=_('Recognised domain'))
    diagnosis = models.TextField(verbose_name=_('Recognised type of page'))

    def __str__(self):
        return _('Page type {hit.diagnosis} at {hit.domain}').format(hit=self)

onion/forms.py
from urllib.parse import urlsplit

from django import forms
from django.core.exceptions import ValidationError
from django.db.models import TextField
from django.utils.translation import ugettext_lazy as _

from onion.models import Hit

list = {'fake': ['americannews.com',
                 'bigamericannews.com',
                 'twitter.com/capnews',
                 'christwire.org',
                 'civictribune.com',
                 'clickhole.com',
                 'creambmp.com',
                 'dcgazette.com',
                 'dailycurrant.com',
                 'dcclothesline.com',
                 'derfmagazine.com',
                 'drudgereport.com.co',
                 'duhprogressive.com',
                 'empirenews.com',
                 'enduringvision.com',
                 'www.cc.com/indecision',
                 'msnbc.co',
                 'msnbc.website',
                 'mediamass.net',
                 'nationalreport.net',
                 'newsbiscuit.com',
                 'news-hound.com',
                 'newsmutiny.com',
                 'politicalears.com',
                 'private-eye.co.uk',
                 'realnewsrightnow.com',
                 'rilenews.com',
                 'sprotspickle.com',
                 'thenewsnerd.com',
                 'theuspatriot.com',
                 'witscience.org', ],
        'satire': ['theonion.com',
                   'amplifyingglass.com',
                   'duffleblog.com',
                   'empiresports.co',
                   'gomerblog.com',
                   'huzlers.com',
                   'itaglive.com',
                   'newslo.com',
                   'thedailymash.co.uk',
                   'borowitzreport.com',
                   'dailybonnet.com',
                   'der-postillon.com',
                   'nahadaily.com',
                   'rockcitytimes.com',
                   'thelapine.ca',
                   'thespoof.com',
                   'weeklyworldnews.com',
                   'worldnewsdailyreport.com',
                   'aszdziennik.pl', ],
        'clickbait': ['21stcenturywire.com',
                      'activistpost.com',
                      'beforeitsnews.com',
                      'bigpzone.com',
                      'chronicle.su',
                      'coasttocoastam.com',
                      'consciouslifenews.com',
                      'conservativeoutfitters.com',
                      'wideawakeamerica.com',
                      'countdowntozerotime.com',
                      'counterpsyops.com',
                      'dailybuzzlive.com',
                      'disclose.tv',
                      'fprnradio.com',
                      'czystejelito.eu',
                      'geoengineeringwatch.org',
                      'globalresearch.ca',
                      'govtslaves.info',
                      'gulagbound.com',
                      'jonesreport.com',
                      'hangthebankers.com',
                      'humansarefree.com',
                      'infowars.com',
                      'intellihub.com',
                      'lewrockwell.com',
                      'libertytalk.fm',
                      'libertyvideos.org',
                      'libertymovementradio.com',
                      'megynkelly.us',
                      'naturalnews.com',
                      'newswire-24.com',
                      'nodisinfo.com',
                      'nowtheendbegins.com',
                      'pakalertpress.com',
                      'politicalblindspot.com',
                      'prisonplanet.com',
                      'prisonplanet.tv',
                      'realfarmacy.com',
                      'redflagnews.com',
                      'truthfrequencyradio.com',
                      'thedailysheeple.com',
                      'therundownlive.com',
                      'unconfirmedsources.com',
                      'veteranstoday.com',
                      'wakingupwisconsin.com',
                      'worldtruth.tv',
                      ],
        'stupid': ['dailymail.co.uk',
                   'fronda.pl']}


class IsItForm(forms.Form):
    uri = forms.CharField(widget=forms.TextInput(attrs={'size': 40}))

    def clean_uri(self):
        cleaned = self.cleaned_data['uri'].lower()
        try:
            split = urlsplit(cleaned).netloc
        except ValueError:
            raise ValidationError(
                _('Invalid link: %(value)s'),
                code='invalid',
                params={'value': cleaned},
            )
        if split:
            return cleaned
        else:
            split = urlsplit('http://' + cleaned).netloc
            if split:
                return 'http://' + cleaned
            else:
                raise ValidationError(
                    _('Invalid link: %(value)s'),
                    code='invalid',
                    params={'value': cleaned},
                )
                # return cleaned

    def isit(self):
        """
        Check if this website is in the domain which is listed

        :return: dict of type of site: bool (is it or not)
        """
        link = self.cleaned_data['uri']
        split = urlsplit(link).netloc
        response = {k: any(v in split for v in list[k]) for k in list.keys()}  # go through all possible lists above
        type_of_page = [k for k in response.keys() if response[k]]
        if not type_of_page:
            type_of_page = 'ok'
        else:
            type_of_page = type_of_page[0]
        response['onion'] = 'theonion.com' in split
        response['page'] = split
        response['type'] = type_of_page
        newhit = Hit(url=link, domain=split, diagnosis=type_of_page)
        newhit.save()
        return response


class SendForm(forms.Form):
    """
    Form for submitting new pages. Contains honeypot for spam prevention.
    """
    name = forms.CharField(label=_("Your Name"), widget=forms.TextInput(attrs={'size': 40}))
    email = forms.EmailField(label=_("Your E-mail"),)
    offending_uri = forms.CharField(label=_("The offending page"), widget=forms.TextInput(attrs={'size': 40}))
    comment = forms.CharField(label=_("Any comments?"), widget=forms.Textarea)
    huny = forms.HiddenInput()

onion/views.py
# Create your views here.
from django.http import JsonResponse
from django.views.generic import FormView

from onion.forms import IsItForm, SendForm
from onion.utils import send_templated_mail


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    """

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'response': form.isit()
            }
            return JsonResponse(data)
        else:
            return response


class IndexView(AjaxableResponseMixin, FormView):
    template_name = 'onion/index.html'
    form_class = IsItForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super(IndexView, self).form_valid(form)


class SendView(FormView):
    template_name = 'onion/send_modal.html'
    form_class = SendForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        """
        Renders an e-mail to `email`.  `template_prefix` identifies the
        e-mail that is to be sent, e.g. "account/email/email_confirmation"
        """
        context = {'name': form.cleaned_data['name'],
                   'email': form.cleaned_data['email'],
                   'offending_url': form.cleaned_data['offending_uri'],
                   'comment': form.cleaned_data['comment'],
                   'request': self.request}
        send_templated_mail(template_prefix='onion/email/submit', from_email='default@isittheonion.com',
                            to_email='the.ktokolwiek@gmail.com', context=context)

        send_templated_mail(template_prefix='onion/email/submit_user', from_email='default@isittheonion.com',
                            to_email=context['email'], context=context)

        return super(SendView, self).form_valid(form)


send = SendView.as_view()

index = IndexView.as_view()

templates/onion/_base.html
{% load i18n %}
{% load staticfiles %}
{% load cookielaw_tags %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"pl" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
      <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
  <![endif]-->
    <link rel="stylesheet" href="{% static "css/main.css" %}">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header page-scroll">
          <a class="navbar-brand page-scroll" href="{% url "onion:index" %}">{% trans "Home" %}</a>
        </div>
        <ul class="nav navbar-nav">
            <li>
                <a class="page-scroll" href="#about">{% trans "About" %}</a>
            </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'two_factor:profile' %}">{% trans "Profile" %}</a>
                </li>
                <li>
                    <a href="{% url 'admin:logout' %}">{% trans "Log out" %}</a>
                </li>
            {% endif %}
        </ul>
      </div>
    </nav>
  <section id="main">
  {% cookielaw_banner %}
  {% block content_wrapper %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  {% endblock %}
  </section>
  <section id="about">
  <div class="container">
  <h2>{% trans "About" %}</h2>
  <p>{% blocktrans %}Sometimes the news are just too good to be true. Sometimes this is because they aren't!{% endblocktrans %}</p>
  <p>{% blocktrans %}This site lets you check against an array of known spoof websites. The list comes from <a href="http://www.fakenewswatch.com/" target="_blank">fakenewswatch.com</a>.{% endblocktrans %}</p>
  </div>

  </section>
      <footer class="stick">
      <div class="container">
      <p class="text-muted top-margin">{% blocktrans %}Lovingly made by <a href="https://twitter.com/thektokolwiek" target="_blank">Łukasz Kopeć</a>. Powered by <a href="https://www.djangoproject.com/" target="_blank">Django</a>.<br/>
            Disclaimer: This site is NOT affiliated with the Onion, the satirical news website.{% endblocktrans %}</p>
      </div>
      </footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="{% static "cookielaw/js/cookielaw.js" %}"></script>
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/scrolling-nav.js" %}"></script>
    {% block extrascripts %}{% endblock %}
</body>
</html>

templates/onion/index.html
{% extends "onion/_base.html" %}
{% load i18n %}
{% block title %}{% trans "Is it the Onion?" %}{% endblock %}
{% block extrascripts %}
    <script>
    $(document).ready(function() {

    // process the form
    $('#isit_form').submit(function(event) {

        // get the form data
        // there are many ways to get this data using jQuery (you can use the class or id also)
        var formData = {
            'uri'              : $('input[name=uri]').val(),
            'csrfmiddlewaretoken': $.cookie('csrftoken'),
        };

        // process the form
        $.ajax({
            type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
            url         : '', // the url where we want to POST
            data        : formData, // our data object
            dataType    : 'json', // what type of data do we expect back from the server
            encode          : true
        })
            // using the done promise callback
            .done(function(data) {
                var resp = data['response'];
                var type = '';
                $('#is_it').find('> div').hide();
                if (resp['onion']) {
                    $('#onion').show();
                    type='onion';
                } else if (resp['clickbait']) {
                    $('#clickbait').show();
                    type='clickbait';
                } else if(resp['fake']) {
                    $('#fake').show();
                    type='fake';
                } else if(resp['satire']) {
                    $('#satire').show();
                    type='satire';
                } else if(resp['stupid']) {
                    $('#stupid').show();
                    type='stupid';
                } else {
                    $('#ok').show();
                    $.get("{% url 'onion:send' %}", function(data) {
                        $('#submitBody').html(data);
                        $('#id_offending_uri').val( $('input[name=uri]').val());
                    } );

                    type='ok';
                }
                $("#"+type+" .domain").html(resp['page']);
                // log data to the console so we can see
                console.log(data);

                // here we will handle errors and validation messages
            });

        // stop the form from submitting the normal way and refreshing the page
        event.preventDefault();
    });

});
    </script>
{% endblock %}
{% block content %}
    <form id="isit_form" action="" method="post">
    {% csrf_token %}
        <div id="big_input" class="row">
            <div class="col-md-12"><h1>{% trans "Is it the Onion?" %}</h1></div>
                {{ form.uri }}
                <button type="submit" name="submit">{% trans "Check" %}</button>
        </div>
    </form>

<div id="is_it" class="row">

    <div id="onion" class="result">
        <h2>{% trans "Yes, it IS the onion!" %}</h2>
        {% trans "Were you expecting something else?" %}
    </div>
    <div id="clickbait" class="result">
        <h2>{% trans "It's NOT the onion, but it is a different <em>clickbait</em> page!" %}</h2>
        {% blocktrans %}
        The page <span class="domain"></span> has been marked as <a href="https://en.wikipedia.org/wiki/Clickbait" target="_blank">clickbait</a>.
            You should probably take their news with a pinch of salt.
        {% endblocktrans %}
        <div class="source"><a href="http://www.fakenewswatch.com/" target="_blank">{% trans "source: fakenewswatch.com" %}</a></div>
    </div>
    <div id="fake" class="result">
        <h2>{% trans "It's NOT the onion, but it is a different <em>fake news</em> page!" %}</h2>
        {% blocktrans %}
        The page <span class="domain"></span> has been marked as <a href="https://en.wikipedia.org/wiki/Fake_news" target="_blank">fake news</a>.
            You should probably take their news with a pinch of salt.
        {% endblocktrans %}
        <div class="source"><a href="http://www.fakenewswatch.com/" target="_blank">{% trans "source: fakenewswatch.com" %}</a></div>
    </div>
    <div id="satire" class="result">
        <h2>{% trans "It's NOT the onion, but it is a different <em>news satire</em> page!" %}</h2>
        {% blocktrans %}
        The page <span class="domain"></span> has been marked as <a href="https://en.wikipedia.org/wiki/News_satire" target="_blank">news satire</a>.
            Although funny, you should probably take their news with a pinch of salt.
        {% endblocktrans %}
        <div class="source"><a href="http://www.fakenewswatch.com/" target="_blank">{% trans "source: fakenewswatch.com" %}</a></div>
    </div>
    <div id="stupid" class="result">
        <h2>{% trans "It's NOT the onion, and strictly speaking not fake, but should you <em>really</em> trust them?" %}</h2>
        {% blocktrans %}
        Seriously, <span class="domain"></span>? You should know better.
        {% endblocktrans %}
    </div>
    <div id="ok" class="result">
        <h2>{% trans "It's NOT the onion!" %}</h2>
        {% blocktrans %}
        You're safe for now! <span class="domain"></span> is not on our list!
            But really, you should check their sources. A couple of helpful links:
            <ul>
<li><a href="http://www.fortliberty.org/hoax-sites.html">Fort Liberty</a></li>
<li><a href="http://p2t2solutions.com/tired-of-being-spoofed-by-fake-news-lies-rumors/">P2T2 Solutions</a></li>
<li><a href="http://LincolnReport.com">Lincoln Report</a></li>
<li><a href="http://www.newrepublic.com/article/118013/satire-news-websites-are-cashing-gullible-outraged-readers">New Republic</a></li>
<li><a href="http://rationalwiki.org/">Rational Wiki</a></li>
<li><a href="http://snopes.com">Snopes</a></li>
<li><a href="http://urbanlegends.about.com/">Urban Legends – About Entertainment</a></li>
</ul>
            If you find it should go on our list, <a data-toggle="modal" data-target="#report">
  let us know!
</a>
        {% endblocktrans %}
    </div>
</div>

<div class="modal fade" id="report" tabindex="-1" role="dialog" aria-labelledby="reportLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="submitBody">
      ...
    </div>
  </div>
</div>
{% endblock %}

templates/onion/send_modal.html
{% load i18n %}
{% load bootstrap3 %}
<form action="{% url "onion:send" %}" method="post">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="{% trans "Close" %}"><span
                aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="reportLabel">{% trans "Report website" %}</h4>
    </div>
    <div class="modal-body">

        {% csrf_token %}
        {% bootstrap_form form %}

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Nevermind!" %}</button>
        <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
    </div>

</form>